config/routes.rb
Rails.application.routes.draw do

  get 'about' => 'welcome#about'

  namespace :api, defaults: { format: :json } do

    resources :events, only: [:create]

  end

  resources :applications

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :users

  root to: 'welcome#index'

end

app/models/application.rb
class Application < ActiveRecord::Base
	belongs_to :user
	has_many :events
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :application
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :applications
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

     def self.from_omniauth(auth)
     	where(provider: auth.provider, uid: auth.id).first_or_create do |user|
     		user.provider = auth.provider
     		user.uid = auth.uid
     		user.email = auth.info.email
     		user.password = Devise.friendly_token[0,20]
     	end
     end
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController

	skip_before_action :verify_authenticity_token

	def create
		@application = Application.find_by(url: request.env['HTTP_ORIGIN'])
		if @application == nil
			render json: "Unregistered application", status: :unprocessable_entity
		else
			@event = @application.events.build(event_params)
			if @event.save
				render json: @event, status: :created
			else
				render @event.errors, status: :unprocessable_entity
			end
		end

	end

end

private

def event_params
	params.require(:event).permit(:name)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def hello

  	render text: "<h1>Hello</h1>"

  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  def index
  	@applications = Application.all
  end

  def show
  	@application = Application.find(params[:id])
    @events = @application.events.group_by(&:name)
  end

  def new
  	@application = Application.new
  end

  def create
  	@application = current_user.applications.new(app_params)
  	if @application.save
  		flash[:notice] = "Application registered successfully"
  		redirect_to applications_path
  	else
  		flash[:error] = "Error registering application, please try again."
  		render :new
  	end

  end

  def edit
  	@application = Application.find(params[:id])
  end

  def update
    @application = Application.find(params[:id])
    if @application.update_attributes(app_params)
      flash[:notice] = "Registration updated successfully"
      redirect_to application_path
    else
      flash[:error] = "Error updating registered application, please try again"
      render :edit
    end

  end

  def destroy
  	@application = Application.find(params[:id])
  	if @application.destroy
  		flash[:notice] = "Application was de-registered successfully"
  		redirect_to applications_path
  	else
  		flash[:error] = "Error deleting the application from Blocmetrics"
  		render :show
  	end

  end

private

def app_params
	params.require(:application).permit(:name, :summary, :URL)
end

end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
	def facebook
		@user = User.from_omniauth(request.env["omniauth.auth"])
		sign_in_and_redirect @user
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/applications/edit.html.erb
<div class="container">
	<div class="page-header">
		<h1>Edit <small>your application details on Blocmetrics</small></h1>
	</div>

		<div class="row">
		<div class="col-md-8">
		
				<%= form_for @application do |f| %>
		
					<div class="form-group">
						<%= f.label :name %>
						<%= f.text_field :name, class: 'form-control', placeholder: "Add your app name here" %>
					</div>

					<div class="form-group">
						<%= f.label :summary %>
						<%= f.text_field :summary, class: 'form-control', placeholder: "Describe your app in a sentence" %>
					</div>

					<div class="form-group">
						<%= f.label :URL %>
						<%= f.text_field :URL, class: 'form-control', placeholder: "Enter the URL of your app here" %>	
					</div>

					<div class="form-group">
						<%= f.submit "Update", class: 'btn btn-success' %>
					</div>

				<% end %>

		</div>
	</div>


</div>

app/views/applications/index.html.erb
<div class="container">
	<div class="page-header">
		<h1>Registered Applications <small>on Blocmetrics</small></h1>
	</div>

	<% @applications.each do |app| %>

	<div class="row">
		<div class="col-md-8">
			<div class="list-group">

			<li class="list-group-item active">App name: <%= app.name %></li>
			<li class="list-group-item">App URL: <%= link_to app.URL %></li>
			<li class="list-group-item">App summary: <%= app.summary %></li>
			<li class="list-group-item">App ID: <%= app.id %></li>
			<li class="list-group-item"><small> registered <%= time_ago_in_words(app.created_at) %> ago<br>
			<%= link_to "View registration", application_path(app.id) %></small></li>

			</div>
		</div>
	</div>

	<% end %>

</div>

app/views/applications/new.html.erb
<div class="container">
	<div class="page-header">
		<h1>Register <small>your application details to Blocmetrics here</small></h1>
	</div>

	<div class="row">
		<div class="col-md-8">
		
				<%= form_for @application do |f| %>
		
					<div class="form-group">
						<%= f.label :name %>
						<%= f.text_field :name, class: 'form-control', placeholder: "Add your app name here" %>
					</div>

					<div class="form-group">
						<%= f.label :summary %>
						<%= f.text_field :summary, class: 'form-control', placeholder: "Describe your app in a sentence" %>
					</div>

					<div class="form-group">
						<%= f.label :URL %>
						<%= f.text_field :URL, class: 'form-control', placeholder: "Enter the URL of your app here" %>	
					</div>

					<div class="form-group">
						<%= f.submit "Add", class: 'btn btn-success' %>
					</div>

				<% end %>

		</div>
	</div>

	
</div>

app/views/applications/show.html.erb
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<%= javascript_include_tag "application", "chartkick" %>

<div class="container">
	<div class="page-header">
		<h1><%= @application.name %><small> </small></h1>
	</div>

	<div class="row">
		<div class="col-md-8">
			<div class="list-group">

			<li class="list-group-item active">App name: <%= @application.name %></li>
			<li class="list-group-item">App URL: <%= link_to @application.URL %></li>
			<li class="list-group-item">App summary: <%= @application.summary %></li>
			<li class="list-group-item"><small> registered <%= time_ago_in_words(@application.created_at) %> ago</small></li>

			</div>

			<hr class="divider">
				
				<%= pie_chart @application.events.group(:name).count %>
				<%= bar_chart @application.events.group(:name).count %>

			<hr class="divider">

				<div class="list-group">
					<li class="list-group-item active"><span class="badge"><%= @application.events.count %></span>Events</li>
					<% @application.events.each do |event| %>
					<li class="list-group-item"><%= event.name %> | <small><small>created at <%= event.created_at %></small></small></li>
					<% end %>
				</div>

			

			<hr class="divider">

			<%= link_to "Edit application details", edit_application_path, class: 'btn btn-primary' %>
			<%= link_to "De-register application", application_path, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to de-register this application?'} %>

		</div>
	</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmetrics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
		<!--<div class= "container">-->

			<nav class="navbar navbar-inverse navbar-static-top">
				<div class="container">
					
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<div class="navbar-brand">Blocmetrics</div>
					</div>
					
					<div id="navbar" class="navbar-collapse collapse">
						<ul>
						<ul class="nav navbar-nav">
							<li class="active"><%= link_to "Home", root_path %></li>
							<li><%= link_to "App Index", applications_path %></li>
							<li><%= link_to "Register an App", new_application_path %></li>
							<!--<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Index<span class="caret"></span></a>
								<ul class="dropdown-menu" role="menu">
									<li><%= link_to "Wikis" %></li>
									<li><%= link_to "About" %></li>
									<li class="divider"></li>
									<li class="dropdown-header">Sub-submenu</li>
									<li><a href="#">Menu-item 3</a></li>
									<li><a href="#">Menu-item 4</a></li>
								</ul>-->
							</li>
						</ul>
									
						<p class="navbar-text pull-right">
						<% if current_user %>
							Logged in
							<%= link_to root_path, class: 'btn btn-default btn-xs' do %>
								<span class="glyphicon glyphicon-user"></span>
							<% end %> 
							<%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-default btn-xs' do %>
								<span class="glyphicon glyphicon-forward"></span>
							<% end %>
						<% else %>
							<%= link_to "Sign In", new_user_session_path %> or
							<%= link_to "Sign Up", new_user_registration_path %>  
						<% end %>
						</p>
					</div>

				</div>			
			</nav>
		
<div class="container">
<% if flash[:notice] %>
	<div class="alert alert-success">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<%= flash[:notice] %>
	</div>
<% elsif flash[:error] %>
	<div class="alert alert-danger">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<%= flash[:error] %>
	</div>
<% elsif flash[:alert] %>
	<div class="alert alert-warning">
		<button type="button" class="close" data-dismiss-"alert">&times;</button>
		<%= flash[:alert] %>
	</div>
	<% end %>
</div>
</div>

<%= yield %>

</body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<div class="container">
	<div class="jumbotron">
	  <h1>Blocmetrics</h1>
	  <p>Blocmetrics </p>
	</div>

	<!--<div class="container marketing">

		<div class="row">
		  <div class="col-lg-4">
		    <h2>Make lists!</h2>
		    <p>Use Blocitoff to make lists of things that need to get done.</p>
		    <p><a class="btn btn-default" href="#" role="button">Click here</a></p>
		  </div>
		  <div class="col-lg-4">
		    <h2>Tick off!</h2>
		    <p>Tick off your lists of things as you go along, by using Blocitoff on a daily basis.</p>
		    <p><a class="btn btn-default" href="#" role="button">Click here</a></p>
		  </div>
		  <div class="col-lg-4">
		    <h2>Feel better!</h2>
		    <p>Blocitoff will make you feel better about being organised in your life.</p>
		    <p><a class="btn btn-default" href="#" role="button">Click here</a></p>
		  </div>
		</div>
	</div>-->
</div>